server {
    listen 80;
    server_name _;

    # Lets us prove that this exact config is deployed
    add_header X-EduSync-Frontend-Config "api-proxy-v1" always;

    root /usr/share/nginx/html;
    index index.html;

    # Forward API requests to backend
    location /api/ {
        proxy_pass https://system-backend.school-system.knoxverse.com;

        proxy_http_version 1.1;

        proxy_ssl_server_name on;
        proxy_ssl_name system-backend.school-system.knoxverse.com;

        proxy_set_header Host system-backend.school-system.knoxverse.com;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # React SPA
    location / {
        try_files $uri $uri/ /index.html;
    }
}
